[project]
name = "100daysofpthon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prettytable>=3.17.0",
]

[tool.uv.workspace]
members = [
    "Day25",
    "DAY18/hirst-painting-start",
]
